### ISSUE TITLE
Error installing version 7

### ISSUE THREAD

**Issue by duramato** [Magisk-Modules-Repo/GoogleDialerFramework#23]
When trying to update to the latest version 7, after downloading the Source Code (Zip) from the releases page, it is showing me `! Unzip error`. 
It seems that something broke the module with the latest updates.

**Comment by TheJulianJES** [comment]
Can you try to install v8?

Link: https://github.com/Magisk-Modules-Repo/GoogleDialerFramework/releases
Make sure to download ``GoogleDialerFramework-v8.zip`` this time.

**Comment by duramato** [comment]
V8 works for me. Installs successfully.
