### ISSUE TITLE
module prop file has wrong version 7 instead of 8

### ISSUE THREAD

**Issue by 00raq00** [Magisk-Modules-Repo/GoogleDialerFramework#24]
https://github.com/Magisk-Modules-Repo/GoogleDialerFramework/blob/bd786fdd16e3ac201e6f0ee6ad488ce74976d130/module.prop#L3

**Comment by TheJulianJES** [comment]
Thanks! I forgot to update it yesterday. It should be fixed now.
(https://github.com/Magisk-Modules-Repo/GoogleDialerFramework/releases/tag/v9 // https://github.com/Magisk-Modules-Repo/GoogleDialerFramework/commit/77e05615ffc2e7b5e5b64b50f4f17e648401a0d6)
