### ISSUE TITLE
Information about the changes performed by the module

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/GoogleDialerFramework#5]
I'd like to understand what are the advantages of installing this module rather than simply installing the apk of Google Dialer.

**Comment by TheJulianJES** [comment]
If you can install the Google Dialer, you don't need this framework as your rom already includes the important files.
However some systems need this in order to install an unmodded Google Dialer apk.

**Comment by MarcAnt01** [comment]
Thanks for the answer, maybe you could add this information to the README, so that people are aware of that😀

**Comment by TheJulianJES** [comment]
Yeah, might be a good idea. I'll add some information when I'm updating the module to the new Magisk template.

**Comment by MarcAnt01** [comment]
OK, in case of problems feel free to contact me, I have already migrated all my Magisk modules without problems
