### ISSUE TITLE
Floating ui not working

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/GoogleDialerFramework#7]

**Comment by olegcarguy** [comment]
I have the same issue

**Comment by MarcAnt01** [comment]
> I have the same issue

The same happens when installing it along with Open Gapps Nano, but after installing stock ones, it works properly

**Comment by olegcarguy** [comment]
Actually fixed my problem by giving the phone app write over the top of apps permission and then got the floating UI

**Comment by TheJulianJES** [comment]
Nice, glad you fixed your issue!

**Comment by MarcAnt01** [comment]
@TheJulianJES two guys tried for me ('cause I have Gapps stock and it'd work the same) and it didn't work for them

**Comment by TheJulianJES** [comment]
That's weird but I don't think that it has anything to do with my module then. :/

**Comment by MarcAnt01** [comment]
Sure, but it'd be great to add some stuff for floating ui

**Comment by TheJulianJES** [comment]
Is the bug still present (with recent versions) of the Google Dialer app in the Play Store?
If yes, please post information about what phone and ROM you're using + the gapps you installed.
Thanks!

**Comment by psyscope** [comment]
No the bugs gone. However have you considered looking at the settings of
the new OnePlus Nord? Since they are defaulting to google dialer.

**Comment by MarcAnt01** [comment]
Haven’t been using the module for a while, sorry. Closing the issue after @psyscope ’s report
