### ISSUE TITLE
Stop working with Android 10

### ISSUE THREAD

**Issue by Mygod** [Magisk-Modules-Repo/GoogleDialerFramework#9]
OxygenOS 10. Was working with 9.

**Comment by TheJulianJES** [comment]
Did the app "uninstall" when you upgraded to Android Q?

**Comment by Mygod** [comment]
Yep and the dialer app won't install on Google play now.

**Comment by Mygod** [comment]
Never mind reinstalled Magisk along with a bunch of other stuff (possibly also cleared GMS data?) and it seems to be working now.

**Comment by TheJulianJES** [comment]
Nice, glad it was "fixed" for you. :)
